../rtl/pkg/npu_config_pkg.sv
../rtl/pkg/npu_spm_pkg.sv
../rtl/sa/int8_dsp_mac_lane.sv
../rtl/sa/pe_int8_single.sv
../rtl/sa/skew_delay_line.sv
../rtl/sa/systolic_array_32x32.sv
../rtl/sa/sa_drain_reorder.sv
../rtl/sa/spm_sa_gemm_i8_core.sv
../rtl/attention/attention_qk_scheduler.sv
../rtl/scheduler/gemm_mode_scheduler.sv
../rtl/bank/uram_lane72.sv
../rtl/bank/uram256_bank.sv
../rtl/bank/bram256_bank.sv
../rtl/loader/a_loader_128_to_256.sv
../rtl/loader/w_loader_128_to_256.sv
../rtl/output/co_output_fifo.sv
../rtl/output/co_metadata_buffer.sv
../rtl/output/co_accumulate.sv
../rtl/output/int32_q8_24_to_fp32.sv
../rtl/output/log8_u16_decoder.sv
../rtl/output/pv_i32_row_normalize.sv
../rtl/output/co_output_convert.sv
../rtl/ctrl/inst_ctrl.sv
../rtl/dma/axi_aligned_read_stream.sv
../rtl/dma/axi_s2mm_writer.sv
../rtl/dma/api_dma_mapper.sv
../rtl/dma/versa_p_direct_dma_backend.sv
../rtl/ctrl/bank_owner.sv
../rtl/top/npu_datapath.sv
../rtl/top/npu_subsystem.sv
../rtl/top/Versa_P_core.sv
../rtl/top/Versa_P.sv
