`default_nettype none

// Vivado IP-packaging wrapper for the SystemVerilog Versa_P top.
// Keep this wrapper Verilog-2001 style: Vivado IP packager handles explicit
// wire/vector ports more reliably than SystemVerilog "wire logic" top ports.
module Versa_P_ip #(
    parameter integer AXIL_ADDR_W = 32,
    parameter integer AXIL_DATA_W = 64,
    parameter integer AXI_ID_W    = 4,
    parameter integer AXI_ADDR_W  = 32,
    parameter integer AXI_DATA_W  = 128,
    parameter integer BANK_DEPTH_WORDS = 16384,
    parameter integer META_WORD128_DEPTH = 2048,
    parameter integer FIFO_DEPTH = 16,
    parameter integer DMA_MAX_BURST_BEATS = 16,
    parameter integer M1_CONTROL_ONLY = 0,
    parameter integer DISABLE_ERROR_CHECKS = 1,
    parameter integer ENABLE_PROFILE = 0,
    parameter integer O_SPLIT_BANK_HALVES = 0,
    parameter integer M1_DONE_LATENCY = 8
) (
    input  wire                     clk_i,
    input  wire                     rst_n_i,

    input  wire [31:0]              s_axi_awaddr,
    input  wire [2:0]               s_axi_awprot,
    input  wire                     s_axi_awvalid,
    output wire                     s_axi_awready,
    input  wire [63:0]              s_axi_wdata,
    input  wire [7:0]               s_axi_wstrb,
    input  wire                     s_axi_wvalid,
    output wire                     s_axi_wready,
    output wire [1:0]               s_axi_bresp,
    output wire                     s_axi_bvalid,
    input  wire                     s_axi_bready,
    input  wire [31:0]              s_axi_araddr,
    input  wire [2:0]               s_axi_arprot,
    input  wire                     s_axi_arvalid,
    output wire                     s_axi_arready,
    output wire [63:0]              s_axi_rdata,
    output wire [1:0]               s_axi_rresp,
    output wire                     s_axi_rvalid,
    input  wire                     s_axi_rready,

    output wire [3:0]               m_axi0_awid,
    output wire [31:0]              m_axi0_awaddr,
    output wire [7:0]               m_axi0_awlen,
    output wire [2:0]               m_axi0_awsize,
    output wire [1:0]               m_axi0_awburst,
    output wire                     m_axi0_awvalid,
    input  wire                     m_axi0_awready,
    output wire [127:0]             m_axi0_wdata,
    output wire [15:0]              m_axi0_wstrb,
    output wire                     m_axi0_wlast,
    output wire                     m_axi0_wvalid,
    input  wire                     m_axi0_wready,
    input  wire [3:0]               m_axi0_bid,
    input  wire [1:0]               m_axi0_bresp,
    input  wire                     m_axi0_bvalid,
    output wire                     m_axi0_bready,
    output wire [3:0]               m_axi0_arid,
    output wire [31:0]              m_axi0_araddr,
    output wire [7:0]               m_axi0_arlen,
    output wire [2:0]               m_axi0_arsize,
    output wire [1:0]               m_axi0_arburst,
    output wire                     m_axi0_arvalid,
    input  wire                     m_axi0_arready,
    input  wire [3:0]               m_axi0_rid,
    input  wire [127:0]             m_axi0_rdata,
    input  wire [1:0]               m_axi0_rresp,
    input  wire                     m_axi0_rlast,
    input  wire                     m_axi0_rvalid,
    output wire                     m_axi0_rready,

    output wire [3:0]               m_axi1_awid,
    output wire [31:0]              m_axi1_awaddr,
    output wire [7:0]               m_axi1_awlen,
    output wire [2:0]               m_axi1_awsize,
    output wire [1:0]               m_axi1_awburst,
    output wire                     m_axi1_awvalid,
    input  wire                     m_axi1_awready,
    output wire [127:0]             m_axi1_wdata,
    output wire [15:0]              m_axi1_wstrb,
    output wire                     m_axi1_wlast,
    output wire                     m_axi1_wvalid,
    input  wire                     m_axi1_wready,
    input  wire [3:0]               m_axi1_bid,
    input  wire [1:0]               m_axi1_bresp,
    input  wire                     m_axi1_bvalid,
    output wire                     m_axi1_bready,
    output wire [3:0]               m_axi1_arid,
    output wire [31:0]              m_axi1_araddr,
    output wire [7:0]               m_axi1_arlen,
    output wire [2:0]               m_axi1_arsize,
    output wire [1:0]               m_axi1_arburst,
    output wire                     m_axi1_arvalid,
    input  wire                     m_axi1_arready,
    input  wire [3:0]               m_axi1_rid,
    input  wire [127:0]             m_axi1_rdata,
    input  wire [1:0]               m_axi1_rresp,
    input  wire                     m_axi1_rlast,
    input  wire                     m_axi1_rvalid,
    output wire                     m_axi1_rready,

    output wire [3:0]               m_axi2_awid,
    output wire [31:0]              m_axi2_awaddr,
    output wire [7:0]               m_axi2_awlen,
    output wire [2:0]               m_axi2_awsize,
    output wire [1:0]               m_axi2_awburst,
    output wire                     m_axi2_awvalid,
    input  wire                     m_axi2_awready,
    output wire [127:0]             m_axi2_wdata,
    output wire [15:0]              m_axi2_wstrb,
    output wire                     m_axi2_wlast,
    output wire                     m_axi2_wvalid,
    input  wire                     m_axi2_wready,
    input  wire [3:0]               m_axi2_bid,
    input  wire [1:0]               m_axi2_bresp,
    input  wire                     m_axi2_bvalid,
    output wire                     m_axi2_bready,
    output wire [3:0]               m_axi2_arid,
    output wire [31:0]              m_axi2_araddr,
    output wire [7:0]               m_axi2_arlen,
    output wire [2:0]               m_axi2_arsize,
    output wire [1:0]               m_axi2_arburst,
    output wire                     m_axi2_arvalid,
    input  wire                     m_axi2_arready,
    input  wire [3:0]               m_axi2_rid,
    input  wire [127:0]             m_axi2_rdata,
    input  wire [1:0]               m_axi2_rresp,
    input  wire                     m_axi2_rlast,
    input  wire                     m_axi2_rvalid,
    output wire                     m_axi2_rready,

    output wire                     irq_o
);
    Versa_P #(
        .AXIL_ADDR_W           (AXIL_ADDR_W),
        .AXIL_DATA_W           (AXIL_DATA_W),
        .AXI_ID_W              (AXI_ID_W),
        .AXI_ADDR_W            (AXI_ADDR_W),
        .AXI_DATA_W            (AXI_DATA_W),
        .BANK_DEPTH_WORDS      (BANK_DEPTH_WORDS),
        .META_WORD128_DEPTH    (META_WORD128_DEPTH),
        .FIFO_DEPTH            (FIFO_DEPTH),
        .DMA_MAX_BURST_BEATS   (DMA_MAX_BURST_BEATS),
        .M1_CONTROL_ONLY       (M1_CONTROL_ONLY != 0),
        .DISABLE_ERROR_CHECKS  (DISABLE_ERROR_CHECKS != 0),
        .ENABLE_PROFILE        (ENABLE_PROFILE != 0),
        .O_SPLIT_BANK_HALVES   (O_SPLIT_BANK_HALVES != 0),
        .M1_DONE_LATENCY       (M1_DONE_LATENCY)
    ) u_versa_p (
        .clk_i                 (clk_i),
        .rst_n_i               (rst_n_i),
        .s_axil_awaddr_i       (s_axi_awaddr),
        .s_axil_awprot_i       (s_axi_awprot),
        .s_axil_awvalid_i      (s_axi_awvalid),
        .s_axil_awready_o      (s_axi_awready),
        .s_axil_wdata_i        (s_axi_wdata),
        .s_axil_wstrb_i        (s_axi_wstrb),
        .s_axil_wvalid_i       (s_axi_wvalid),
        .s_axil_wready_o       (s_axi_wready),
        .s_axil_bresp_o        (s_axi_bresp),
        .s_axil_bvalid_o       (s_axi_bvalid),
        .s_axil_bready_i       (s_axi_bready),
        .s_axil_araddr_i       (s_axi_araddr),
        .s_axil_arprot_i       (s_axi_arprot),
        .s_axil_arvalid_i      (s_axi_arvalid),
        .s_axil_arready_o      (s_axi_arready),
        .s_axil_rdata_o        (s_axi_rdata),
        .s_axil_rresp_o        (s_axi_rresp),
        .s_axil_rvalid_o       (s_axi_rvalid),
        .s_axil_rready_i       (s_axi_rready),
        .m00_axi_awid_o        (m_axi0_awid),
        .m00_axi_awaddr_o      (m_axi0_awaddr),
        .m00_axi_awlen_o       (m_axi0_awlen),
        .m00_axi_awsize_o      (m_axi0_awsize),
        .m00_axi_awburst_o     (m_axi0_awburst),
        .m00_axi_awvalid_o     (m_axi0_awvalid),
        .m00_axi_awready_i     (m_axi0_awready),
        .m00_axi_wdata_o       (m_axi0_wdata),
        .m00_axi_wstrb_o       (m_axi0_wstrb),
        .m00_axi_wlast_o       (m_axi0_wlast),
        .m00_axi_wvalid_o      (m_axi0_wvalid),
        .m00_axi_wready_i      (m_axi0_wready),
        .m00_axi_bid_i         (m_axi0_bid),
        .m00_axi_bresp_i       (m_axi0_bresp),
        .m00_axi_bvalid_i      (m_axi0_bvalid),
        .m00_axi_bready_o      (m_axi0_bready),
        .m00_axi_arid_o        (m_axi0_arid),
        .m00_axi_araddr_o      (m_axi0_araddr),
        .m00_axi_arlen_o       (m_axi0_arlen),
        .m00_axi_arsize_o      (m_axi0_arsize),
        .m00_axi_arburst_o     (m_axi0_arburst),
        .m00_axi_arvalid_o     (m_axi0_arvalid),
        .m00_axi_arready_i     (m_axi0_arready),
        .m00_axi_rid_i         (m_axi0_rid),
        .m00_axi_rdata_i       (m_axi0_rdata),
        .m00_axi_rresp_i       (m_axi0_rresp),
        .m00_axi_rlast_i       (m_axi0_rlast),
        .m00_axi_rvalid_i      (m_axi0_rvalid),
        .m00_axi_rready_o      (m_axi0_rready),
        .m01_axi_awid_o        (m_axi1_awid),
        .m01_axi_awaddr_o      (m_axi1_awaddr),
        .m01_axi_awlen_o       (m_axi1_awlen),
        .m01_axi_awsize_o      (m_axi1_awsize),
        .m01_axi_awburst_o     (m_axi1_awburst),
        .m01_axi_awvalid_o     (m_axi1_awvalid),
        .m01_axi_awready_i     (m_axi1_awready),
        .m01_axi_wdata_o       (m_axi1_wdata),
        .m01_axi_wstrb_o       (m_axi1_wstrb),
        .m01_axi_wlast_o       (m_axi1_wlast),
        .m01_axi_wvalid_o      (m_axi1_wvalid),
        .m01_axi_wready_i      (m_axi1_wready),
        .m01_axi_bid_i         (m_axi1_bid),
        .m01_axi_bresp_i       (m_axi1_bresp),
        .m01_axi_bvalid_i      (m_axi1_bvalid),
        .m01_axi_bready_o      (m_axi1_bready),
        .m01_axi_arid_o        (m_axi1_arid),
        .m01_axi_araddr_o      (m_axi1_araddr),
        .m01_axi_arlen_o       (m_axi1_arlen),
        .m01_axi_arsize_o      (m_axi1_arsize),
        .m01_axi_arburst_o     (m_axi1_arburst),
        .m01_axi_arvalid_o     (m_axi1_arvalid),
        .m01_axi_arready_i     (m_axi1_arready),
        .m01_axi_rid_i         (m_axi1_rid),
        .m01_axi_rdata_i       (m_axi1_rdata),
        .m01_axi_rresp_i       (m_axi1_rresp),
        .m01_axi_rlast_i       (m_axi1_rlast),
        .m01_axi_rvalid_i      (m_axi1_rvalid),
        .m01_axi_rready_o      (m_axi1_rready),
        .m02_axi_awid_o        (m_axi2_awid),
        .m02_axi_awaddr_o      (m_axi2_awaddr),
        .m02_axi_awlen_o       (m_axi2_awlen),
        .m02_axi_awsize_o      (m_axi2_awsize),
        .m02_axi_awburst_o     (m_axi2_awburst),
        .m02_axi_awvalid_o     (m_axi2_awvalid),
        .m02_axi_awready_i     (m_axi2_awready),
        .m02_axi_wdata_o       (m_axi2_wdata),
        .m02_axi_wstrb_o       (m_axi2_wstrb),
        .m02_axi_wlast_o       (m_axi2_wlast),
        .m02_axi_wvalid_o      (m_axi2_wvalid),
        .m02_axi_wready_i      (m_axi2_wready),
        .m02_axi_bid_i         (m_axi2_bid),
        .m02_axi_bresp_i       (m_axi2_bresp),
        .m02_axi_bvalid_i      (m_axi2_bvalid),
        .m02_axi_bready_o      (m_axi2_bready),
        .m02_axi_arid_o        (m_axi2_arid),
        .m02_axi_araddr_o      (m_axi2_araddr),
        .m02_axi_arlen_o       (m_axi2_arlen),
        .m02_axi_arsize_o      (m_axi2_arsize),
        .m02_axi_arburst_o     (m_axi2_arburst),
        .m02_axi_arvalid_o     (m_axi2_arvalid),
        .m02_axi_arready_i     (m_axi2_arready),
        .m02_axi_rid_i         (m_axi2_rid),
        .m02_axi_rdata_i       (m_axi2_rdata),
        .m02_axi_rresp_i       (m_axi2_rresp),
        .m02_axi_rlast_i       (m_axi2_rlast),
        .m02_axi_rvalid_i      (m_axi2_rvalid),
        .m02_axi_rready_o      (m_axi2_rready),
        .irq_o                 (irq_o)
    );
endmodule

`default_nettype wire
