`timescale 1ns / 1ps

module T_NPU_FPGA_v #(
    parameter integer RF_DATA_WIDTH        = 64,
    parameter integer MMIO_AXI_DATA_WIDTH  = 64,
    parameter integer MMIO_AXI_ADDR_WIDTH  = 32,
    parameter integer AXI_ID_WIDTH         = 4,
    parameter integer AXI_ADDR_WIDTH       = 32,
    parameter integer AXI_DATA_WIDTH       = 128,
    parameter integer PE_WIDTH             = 16,
    parameter integer PE_DATA_WIDTH        = 8,
    parameter integer PE_DATA_WIDTH_IN     = 8,
    parameter integer PE_DATA_WIDTH_OUT    = 32,
    parameter integer SPM_SIZE             = 524288, // 1 << 19
    parameter integer RD_PORTS             = 2,
    parameter integer ACC_SIZE             = 524288, // 1 << 19
    parameter signed [31:0] ALPHA_1        = 32'sd6656,
    parameter signed [31:0] ALPHA_2        = 32'sd13312,
    parameter signed [31:0] ALPHA_3        = 32'sd656,
    parameter integer PE_FPGA_DSP          = 1,
    parameter integer DSP_PE_NUM           = (PE_FPGA_DSP ? PE_WIDTH * PE_WIDTH : 0),
    parameter integer SPM_FPGA_SRAM        = 1,
    parameter integer GELU_NUM             = 4,
    parameter integer DISABLE_SYSTOLIC_ARRAY    = 1,
    parameter integer DISABLE_ACCUMULATOR       = 1,
    parameter integer DISABLE_GEMV              = 0,
    parameter integer DISABLE_SFU               = 1,
    parameter integer DISABLE_SOFTMAX           = 1,
    parameter integer DISABLE_GELU              = 1,
    parameter integer DISABLE_LAYERNORM         = 1,
    parameter integer DISABLE_RESAMPLE          = 1,
    parameter integer DISABLE_TRANSPOSE         = 1,
    parameter integer DISABLE_IM2COL            = 1,
    parameter integer AXI_MAX_BURST_BEATS       = 16,
    parameter integer AXI_MAX_OUTSTANDING       = 16,
    parameter integer DISABLE_MVIN_INT8_TO_INT32 = 1,
    parameter integer DISABLE_ACC_INT32_TO_INT8  = 1,
    parameter integer DISABLE_ACC_TO_SPM_PATH    = 1,
    parameter integer DISABLE_DECODE_ROPE        = 0,
    parameter integer DISABLE_DECODE_SOFTMAX     = 0,
    parameter integer DISABLE_DECODE_KV_QUANT    = 0,
    parameter integer ENABLE_PROFILE_COUNTERS    = 1,
    parameter integer ENABLE_DETAILED_ERROR_STATUS = 1
)(
    input  wire                                  clk,
    input  wire                                  rst_n,
    
    // AXI-Lite interface
    input  wire [MMIO_AXI_ADDR_WIDTH-1 : 0]      s_axi_awaddr,
    input  wire [2 : 0]                          s_axi_awprot,
    input  wire                                  s_axi_awvalid,
    output wire                                  s_axi_awready,
    
    input  wire [MMIO_AXI_DATA_WIDTH-1 : 0]      s_axi_wdata,
    input  wire [(MMIO_AXI_DATA_WIDTH/8)-1 : 0]  s_axi_wstrb,
    input  wire                                  s_axi_wvalid,
    output wire                                  s_axi_wready,
    
    output wire [1 : 0]                          s_axi_bresp,
    output wire                                  s_axi_bvalid,
    input  wire                                  s_axi_bready,
    
    input  wire [MMIO_AXI_ADDR_WIDTH-1 : 0]      s_axi_araddr,
    input  wire [2 : 0]                          s_axi_arprot,
    input  wire                                  s_axi_arvalid,
    output wire                                  s_axi_arready,

    output wire [MMIO_AXI_DATA_WIDTH-1 : 0]      s_axi_rdata,
    output wire [1 : 0]                          s_axi_rresp,
    output wire                                  s_axi_rvalid,
    input  wire                                  s_axi_rready,

    output wire                                  irq,

    // DMA0 AXI-4 interface
    output wire [AXI_ID_WIDTH-1 : 0]             m_axi0_awid,
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME m_axi0, PROTOCOL AXI4, DATA_WIDTH 128, ADDR_WIDTH 32, ID_WIDTH 4, READ_WRITE_MODE READ_WRITE, SUPPORTS_NARROW_BURST 1, MAX_BURST_LENGTH 16, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16" *)
    output wire [AXI_ADDR_WIDTH-1 : 0]           m_axi0_awaddr,
    output wire [7 : 0]                          m_axi0_awlen,
    output wire [2 : 0]                          m_axi0_awsize,
    output wire [1 : 0]                          m_axi0_awburst,
    output wire                                  m_axi0_awvalid,
    input  wire                                  m_axi0_awready,

    output wire [AXI_DATA_WIDTH-1 : 0]           m_axi0_wdata,
    output wire [AXI_DATA_WIDTH/8-1 : 0]         m_axi0_wstrb,
    output wire                                  m_axi0_wlast,
    output wire                                  m_axi0_wvalid,
    input  wire                                  m_axi0_wready,

    input  wire [AXI_ID_WIDTH-1 : 0]             m_axi0_bid,
    input  wire [1 : 0]                          m_axi0_bresp,
    input  wire                                  m_axi0_bvalid,
    output wire                                  m_axi0_bready,

    output wire [AXI_ID_WIDTH-1 : 0]             m_axi0_arid,
    output wire [AXI_ADDR_WIDTH-1 : 0]           m_axi0_araddr,
    output wire [7 : 0]                          m_axi0_arlen,
    output wire [2 : 0]                          m_axi0_arsize,
    output wire [1 : 0]                          m_axi0_arburst,
    output wire                                  m_axi0_arvalid,
    input  wire                                  m_axi0_arready,

    input  wire [AXI_ID_WIDTH-1 : 0]             m_axi0_rid,
    input  wire [AXI_DATA_WIDTH-1 : 0]           m_axi0_rdata,
    input  wire [1 : 0]                          m_axi0_rresp,
    input  wire                                  m_axi0_rlast,
    input  wire                                  m_axi0_rvalid,
    output wire                                  m_axi0_rready,

    // DMA1 AXI-4 interface
    output wire [AXI_ID_WIDTH-1 : 0]             m_axi1_awid,
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME m_axi1, PROTOCOL AXI4, DATA_WIDTH 128, ADDR_WIDTH 32, ID_WIDTH 4, READ_WRITE_MODE READ_WRITE, SUPPORTS_NARROW_BURST 1, MAX_BURST_LENGTH 16, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16" *)
    output wire [AXI_ADDR_WIDTH-1 : 0]           m_axi1_awaddr,
    output wire [7 : 0]                          m_axi1_awlen,
    output wire [2 : 0]                          m_axi1_awsize,
    output wire [1 : 0]                          m_axi1_awburst,
    output wire                                  m_axi1_awvalid,
    input  wire                                  m_axi1_awready,

    output wire [AXI_DATA_WIDTH-1 : 0]           m_axi1_wdata,
    output wire [AXI_DATA_WIDTH/8-1 : 0]         m_axi1_wstrb,
    output wire                                  m_axi1_wlast,
    output wire                                  m_axi1_wvalid,
    input  wire                                  m_axi1_wready,

    input  wire [AXI_ID_WIDTH-1 : 0]             m_axi1_bid,
    input  wire [1 : 0]                          m_axi1_bresp,
    input  wire                                  m_axi1_bvalid,
    output wire                                  m_axi1_bready,

    output wire [AXI_ID_WIDTH-1 : 0]             m_axi1_arid,
    output wire [AXI_ADDR_WIDTH-1 : 0]           m_axi1_araddr,
    output wire [7 : 0]                          m_axi1_arlen,
    output wire [2 : 0]                          m_axi1_arsize,
    output wire [1 : 0]                          m_axi1_arburst,
    output wire                                  m_axi1_arvalid,
    input  wire                                  m_axi1_arready,

    input  wire [AXI_ID_WIDTH-1 : 0]             m_axi1_rid,
    input  wire [AXI_DATA_WIDTH-1 : 0]           m_axi1_rdata,
    input  wire [1 : 0]                          m_axi1_rresp,
    input  wire                                  m_axi1_rlast,
    input  wire                                  m_axi1_rvalid,
    output wire                                  m_axi1_rready,

    // DMA2 AXI-4 interface
    output wire [AXI_ID_WIDTH-1 : 0]             m_axi2_awid,
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME m_axi2, PROTOCOL AXI4, DATA_WIDTH 128, ADDR_WIDTH 32, ID_WIDTH 4, READ_WRITE_MODE READ_WRITE, SUPPORTS_NARROW_BURST 1, MAX_BURST_LENGTH 16, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16" *)
    output wire [AXI_ADDR_WIDTH-1 : 0]           m_axi2_awaddr,
    output wire [7 : 0]                          m_axi2_awlen,
    output wire [2 : 0]                          m_axi2_awsize,
    output wire [1 : 0]                          m_axi2_awburst,
    output wire                                  m_axi2_awvalid,
    input  wire                                  m_axi2_awready,

    output wire [AXI_DATA_WIDTH-1 : 0]           m_axi2_wdata,
    output wire [AXI_DATA_WIDTH/8-1 : 0]         m_axi2_wstrb,
    output wire                                  m_axi2_wlast,
    output wire                                  m_axi2_wvalid,
    input  wire                                  m_axi2_wready,

    input  wire [AXI_ID_WIDTH-1 : 0]             m_axi2_bid,
    input  wire [1 : 0]                          m_axi2_bresp,
    input  wire                                  m_axi2_bvalid,
    output wire                                  m_axi2_bready,

    output wire [AXI_ID_WIDTH-1 : 0]             m_axi2_arid,
    output wire [AXI_ADDR_WIDTH-1 : 0]           m_axi2_araddr,
    output wire [7 : 0]                          m_axi2_arlen,
    output wire [2 : 0]                          m_axi2_arsize,
    output wire [1 : 0]                          m_axi2_arburst,
    output wire                                  m_axi2_arvalid,
    input  wire                                  m_axi2_arready,

    input  wire [AXI_ID_WIDTH-1 : 0]             m_axi2_rid,
    input  wire [AXI_DATA_WIDTH-1 : 0]           m_axi2_rdata,
    input  wire [1 : 0]                          m_axi2_rresp,
    input  wire                                  m_axi2_rlast,
    input  wire                                  m_axi2_rvalid,
    output wire                                  m_axi2_rready,

    // DMA3 AXI-4 interface
    output wire [AXI_ID_WIDTH-1 : 0]             m_axi3_awid,
    (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME m_axi3, PROTOCOL AXI4, DATA_WIDTH 128, ADDR_WIDTH 32, ID_WIDTH 4, READ_WRITE_MODE READ_WRITE, SUPPORTS_NARROW_BURST 1, MAX_BURST_LENGTH 16, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16" *)
    output wire [AXI_ADDR_WIDTH-1 : 0]           m_axi3_awaddr,
    output wire [7 : 0]                          m_axi3_awlen,
    output wire [2 : 0]                          m_axi3_awsize,
    output wire [1 : 0]                          m_axi3_awburst,
    output wire                                  m_axi3_awvalid,
    input  wire                                  m_axi3_awready,

    output wire [AXI_DATA_WIDTH-1 : 0]           m_axi3_wdata,
    output wire [AXI_DATA_WIDTH/8-1 : 0]         m_axi3_wstrb,
    output wire                                  m_axi3_wlast,
    output wire                                  m_axi3_wvalid,
    input  wire                                  m_axi3_wready,

    input  wire [AXI_ID_WIDTH-1 : 0]             m_axi3_bid,
    input  wire [1 : 0]                          m_axi3_bresp,
    input  wire                                  m_axi3_bvalid,
    output wire                                  m_axi3_bready,

    output wire [AXI_ID_WIDTH-1 : 0]             m_axi3_arid,
    output wire [AXI_ADDR_WIDTH-1 : 0]           m_axi3_araddr,
    output wire [7 : 0]                          m_axi3_arlen,
    output wire [2 : 0]                          m_axi3_arsize,
    output wire [1 : 0]                          m_axi3_arburst,
    output wire                                  m_axi3_arvalid,
    input  wire                                  m_axi3_arready,

    input  wire [AXI_ID_WIDTH-1 : 0]             m_axi3_rid,
    input  wire [AXI_DATA_WIDTH-1 : 0]           m_axi3_rdata,
    input  wire [1 : 0]                          m_axi3_rresp,
    input  wire                                  m_axi3_rlast,
    input  wire                                  m_axi3_rvalid,
    output wire                                  m_axi3_rready,
    output wire                                  busy
);
    T_NPU_FPGA #(
        .RF_DATA_WIDTH(RF_DATA_WIDTH),
        .MMIO_AXI_DATA_WIDTH(MMIO_AXI_DATA_WIDTH),
        .MMIO_AXI_ADDR_WIDTH(MMIO_AXI_ADDR_WIDTH),
        .AXI_ID_WIDTH(AXI_ID_WIDTH),
        .AXI_ADDR_WIDTH(AXI_ADDR_WIDTH),
        .AXI_DATA_WIDTH(AXI_DATA_WIDTH),
        .PE_WIDTH(PE_WIDTH),
        .PE_DATA_WIDTH(PE_DATA_WIDTH),
        .PE_DATA_WIDTH_IN(PE_DATA_WIDTH_IN),
        .PE_DATA_WIDTH_OUT(PE_DATA_WIDTH_OUT),
        .SPM_SIZE(SPM_SIZE),
        .RD_PORTS(RD_PORTS),
        .ACC_SIZE(ACC_SIZE),
        .AXI_MAX_BURST_BEATS(AXI_MAX_BURST_BEATS),
        .AXI_MAX_OUTSTANDING(AXI_MAX_OUTSTANDING),
        .ALPHA_1(ALPHA_1),
        .ALPHA_2(ALPHA_2),
        .ALPHA_3(ALPHA_3),
        .PE_FPGA_DSP(PE_FPGA_DSP),
        .DSP_PE_NUM(DSP_PE_NUM),
        .SPM_FPGA_SRAM(SPM_FPGA_SRAM),
        .GELU_NUM(GELU_NUM),
        .DISABLE_SYSTOLIC_ARRAY(DISABLE_SYSTOLIC_ARRAY),
        .DISABLE_ACCUMULATOR(DISABLE_ACCUMULATOR),
        .DISABLE_GEMV(DISABLE_GEMV),
        .DISABLE_SFU(DISABLE_SFU),
        .DISABLE_SOFTMAX(DISABLE_SOFTMAX),
        .DISABLE_GELU(DISABLE_GELU),
        .DISABLE_LAYERNORM(DISABLE_LAYERNORM),
        .DISABLE_RESAMPLE(DISABLE_RESAMPLE),
        .DISABLE_TRANSPOSE(DISABLE_TRANSPOSE),
        .DISABLE_IM2COL(DISABLE_IM2COL),
        .DISABLE_MVIN_INT8_TO_INT32(DISABLE_MVIN_INT8_TO_INT32),
        .DISABLE_ACC_INT32_TO_INT8(DISABLE_ACC_INT32_TO_INT8),
        .DISABLE_ACC_TO_SPM_PATH(DISABLE_ACC_TO_SPM_PATH),
        .DISABLE_DECODE_ROPE(DISABLE_DECODE_ROPE),
        .DISABLE_DECODE_SOFTMAX(DISABLE_DECODE_SOFTMAX),
        .DISABLE_DECODE_KV_QUANT(DISABLE_DECODE_KV_QUANT),
        .ENABLE_PROFILE_COUNTERS(ENABLE_PROFILE_COUNTERS),
        .ENABLE_DETAILED_ERROR_STATUS(ENABLE_DETAILED_ERROR_STATUS)
    ) inst_T_NPU_FPGA (
        .clk(clk),
        .rst_n(rst_n),
        .s_axi_awaddr(s_axi_awaddr),
        .s_axi_awprot(s_axi_awprot),
        .s_axi_awvalid(s_axi_awvalid),
        .s_axi_awready(s_axi_awready),
        .s_axi_wdata(s_axi_wdata),
        .s_axi_wstrb(s_axi_wstrb),
        .s_axi_wvalid(s_axi_wvalid),
        .s_axi_wready(s_axi_wready),
        .s_axi_bresp(s_axi_bresp),
        .s_axi_bvalid(s_axi_bvalid),
        .s_axi_bready(s_axi_bready),
        .s_axi_araddr(s_axi_araddr),
        .s_axi_arprot(s_axi_arprot),
        .s_axi_arvalid(s_axi_arvalid),
        .s_axi_arready(s_axi_arready),
        .s_axi_rdata(s_axi_rdata),
        .s_axi_rresp(s_axi_rresp),
        .s_axi_rvalid(s_axi_rvalid),
        .s_axi_rready(s_axi_rready),
        .irq(irq),
        .m_axi0_awid(m_axi0_awid),
        .m_axi0_awaddr(m_axi0_awaddr),
        .m_axi0_awlen(m_axi0_awlen),
        .m_axi0_awsize(m_axi0_awsize),
        .m_axi0_awburst(m_axi0_awburst),
        .m_axi0_awvalid(m_axi0_awvalid),
        .m_axi0_awready(m_axi0_awready),
        .m_axi0_wdata(m_axi0_wdata),
        .m_axi0_wstrb(m_axi0_wstrb),
        .m_axi0_wlast(m_axi0_wlast),
        .m_axi0_wvalid(m_axi0_wvalid),
        .m_axi0_wready(m_axi0_wready),
        .m_axi0_bid(m_axi0_bid),
        .m_axi0_bresp(m_axi0_bresp),
        .m_axi0_bvalid(m_axi0_bvalid),
        .m_axi0_bready(m_axi0_bready),
        .m_axi0_arid(m_axi0_arid),
        .m_axi0_araddr(m_axi0_araddr),
        .m_axi0_arlen(m_axi0_arlen),
        .m_axi0_arsize(m_axi0_arsize),
        .m_axi0_arburst(m_axi0_arburst),
        .m_axi0_arvalid(m_axi0_arvalid),
        .m_axi0_arready(m_axi0_arready),
        .m_axi0_rid(m_axi0_rid),
        .m_axi0_rdata(m_axi0_rdata),
        .m_axi0_rresp(m_axi0_rresp),
        .m_axi0_rlast(m_axi0_rlast),
        .m_axi0_rvalid(m_axi0_rvalid),
        .m_axi0_rready(m_axi0_rready),
        .m_axi1_awid(m_axi1_awid),
        .m_axi1_awaddr(m_axi1_awaddr),
        .m_axi1_awlen(m_axi1_awlen),
        .m_axi1_awsize(m_axi1_awsize),
        .m_axi1_awburst(m_axi1_awburst),
        .m_axi1_awvalid(m_axi1_awvalid),
        .m_axi1_awready(m_axi1_awready),
        .m_axi1_wdata(m_axi1_wdata),
        .m_axi1_wstrb(m_axi1_wstrb),
        .m_axi1_wlast(m_axi1_wlast),
        .m_axi1_wvalid(m_axi1_wvalid),
        .m_axi1_wready(m_axi1_wready),
        .m_axi1_bid(m_axi1_bid),
        .m_axi1_bresp(m_axi1_bresp),
        .m_axi1_bvalid(m_axi1_bvalid),
        .m_axi1_bready(m_axi1_bready),
        .m_axi1_arid(m_axi1_arid),
        .m_axi1_araddr(m_axi1_araddr),
        .m_axi1_arlen(m_axi1_arlen),
        .m_axi1_arsize(m_axi1_arsize),
        .m_axi1_arburst(m_axi1_arburst),
        .m_axi1_arvalid(m_axi1_arvalid),
        .m_axi1_arready(m_axi1_arready),
        .m_axi1_rid(m_axi1_rid),
        .m_axi1_rdata(m_axi1_rdata),
        .m_axi1_rresp(m_axi1_rresp),
        .m_axi1_rlast(m_axi1_rlast),
        .m_axi1_rvalid(m_axi1_rvalid),
        .m_axi1_rready(m_axi1_rready),
        .m_axi2_awid(m_axi2_awid),
        .m_axi2_awaddr(m_axi2_awaddr),
        .m_axi2_awlen(m_axi2_awlen),
        .m_axi2_awsize(m_axi2_awsize),
        .m_axi2_awburst(m_axi2_awburst),
        .m_axi2_awvalid(m_axi2_awvalid),
        .m_axi2_awready(m_axi2_awready),
        .m_axi2_wdata(m_axi2_wdata),
        .m_axi2_wstrb(m_axi2_wstrb),
        .m_axi2_wlast(m_axi2_wlast),
        .m_axi2_wvalid(m_axi2_wvalid),
        .m_axi2_wready(m_axi2_wready),
        .m_axi2_bid(m_axi2_bid),
        .m_axi2_bresp(m_axi2_bresp),
        .m_axi2_bvalid(m_axi2_bvalid),
        .m_axi2_bready(m_axi2_bready),
        .m_axi2_arid(m_axi2_arid),
        .m_axi2_araddr(m_axi2_araddr),
        .m_axi2_arlen(m_axi2_arlen),
        .m_axi2_arsize(m_axi2_arsize),
        .m_axi2_arburst(m_axi2_arburst),
        .m_axi2_arvalid(m_axi2_arvalid),
        .m_axi2_arready(m_axi2_arready),
        .m_axi2_rid(m_axi2_rid),
        .m_axi2_rdata(m_axi2_rdata),
        .m_axi2_rresp(m_axi2_rresp),
        .m_axi2_rlast(m_axi2_rlast),
        .m_axi2_rvalid(m_axi2_rvalid),
        .m_axi2_rready(m_axi2_rready),
        .m_axi3_awid(m_axi3_awid),
        .m_axi3_awaddr(m_axi3_awaddr),
        .m_axi3_awlen(m_axi3_awlen),
        .m_axi3_awsize(m_axi3_awsize),
        .m_axi3_awburst(m_axi3_awburst),
        .m_axi3_awvalid(m_axi3_awvalid),
        .m_axi3_awready(m_axi3_awready),
        .m_axi3_wdata(m_axi3_wdata),
        .m_axi3_wstrb(m_axi3_wstrb),
        .m_axi3_wlast(m_axi3_wlast),
        .m_axi3_wvalid(m_axi3_wvalid),
        .m_axi3_wready(m_axi3_wready),
        .m_axi3_bid(m_axi3_bid),
        .m_axi3_bresp(m_axi3_bresp),
        .m_axi3_bvalid(m_axi3_bvalid),
        .m_axi3_bready(m_axi3_bready),
        .m_axi3_arid(m_axi3_arid),
        .m_axi3_araddr(m_axi3_araddr),
        .m_axi3_arlen(m_axi3_arlen),
        .m_axi3_arsize(m_axi3_arsize),
        .m_axi3_arburst(m_axi3_arburst),
        .m_axi3_arvalid(m_axi3_arvalid),
        .m_axi3_arready(m_axi3_arready),
        .m_axi3_rid(m_axi3_rid),
        .m_axi3_rdata(m_axi3_rdata),
        .m_axi3_rresp(m_axi3_rresp),
        .m_axi3_rlast(m_axi3_rlast),
        .m_axi3_rvalid(m_axi3_rvalid),
        .m_axi3_rready(m_axi3_rready),
        .busy(busy)
    );

endmodule
